services:
  postgres:
    image: postgres:15-alpine
    container_name: gym_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: gym_tracker
    ports:
      - "5432:5432"
    volumes:
      - gymdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .                 
      dockerfile: Dockerfile     
      target: backend            
    container_name: gym_backend
    ports:
      - "8085:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:secretpassword@postgres:5432/gym_tracker
    volumes:
      - ./apps/backend:/app
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .                 
      dockerfile: Dockerfile     
      target: frontend           
    container_name: gym_frontend
    ports:
      - "3005:80"
    depends_on:
      - backend

volumes:
  gymdata: